#!/bin/bash

# Define variables
DOMAIN="moealsir.tech"
NGINX_SITES_AVAILABLE="/etc/nginx/sites-available"
NGINX_SITES_ENABLED="/etc/nginx/sites-enabled"
NGINX_RELOAD="sudo systemctl reload nginx"

# Cloudflare API credentials
CLOUDFLARE_API_TOKEN="y4YPReT2-KiliGfiRhG_sgXwR0BXFh-Zqp9VoPDk"
CLOUDFLARE_ZONE_ID="db2a6826a77fbf23e7c7519ac458cc06"

# Function to create a new subdomain locally
create_subdomain_local() {
    local subdomain="$1"

    # Create subdomain folder by copying the main domain folder
    sudo cp -r "/var/www/$DOMAIN" "/var/www/$subdomain.$DOMAIN"

    # Create Nginx configuration file for the subdomain
    sudo tee "$NGINX_SITES_AVAILABLE/$subdomain.$DOMAIN" > /dev/null <<EOF
server {
    listen 80;
    root /var/www/$subdomain.$DOMAIN;
    index index.html index.htm index.nginx-debian.html;
    server_name $subdomain.$DOMAIN www.$subdomain.$DOMAIN;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

    # Create symbolic link to enable the site
    sudo ln -s "$NGINX_SITES_AVAILABLE/$subdomain.$DOMAIN" "$NGINX_SITES_ENABLED/$subdomain.$DOMAIN"

    # Adjust permissions
    sudo chown -R $USER:$USER "/var/www/$DOMAIN/html"
    sudo chown -R $USER:$USER "/var/www/$subdomain.$DOMAIN/html"
    sudo chmod -R 755 "/var/www/$DOMAIN"
    sudo chmod -R 755 "/var/www/$subdomain.$DOMAIN"

    # Reload Nginx
    $NGINX_RELOAD

    echo "Subdomain $subdomain.$DOMAIN created locally successfully."
}

# Function to delete a subdomain locally
delete_subdomain_local() {
    local subdomain="$1"

    SUBDOMAIN_CONF="$NGINX_SITES_AVAILABLE/$subdomain.$DOMAIN"
    SUBDOMAIN_DIR="/var/www/$subdomain.$DOMAIN"

    # Remove Nginx configuration file
    sudo rm -f "$SUBDOMAIN_CONF"

    # Remove symbolic link from sites-enabled
    sudo rm -f "$NGINX_SITES_ENABLED/$subdomain.$DOMAIN"

    # Reload Nginx
    $NGINX_RELOAD

    # Remove document root directory
    sudo rm -rf "$SUBDOMAIN_DIR"

    echo "Subdomain $subdomain.$DOMAIN deleted locally successfully."
}

# Function to create a DNS record in Cloudflare
create_dns_record_cloudflare() {
    local subdomain="$1"
    local record_type="CNAME"
    local ip_address="54.226.6.57"  # Replace with your server's IP address

    # Send API request to create DNS record
    curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records" \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    -H "Content-Type: application/json" \
    --data "{\"type\":\"$record_type\",\"name\":\"$subdomain.$DOMAIN\",\"content\":\"$ip_address\",\"ttl\":120,\"proxied\":true}" \
    | jq -r '.success'
}

# Function to delete a DNS record in Cloudflare
delete_dns_record_cloudflare() {
    local subdomain="$1"

    # Send API request to fetch DNS record ID
    local dns_record_ids=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records?type=A&name=$subdomain.$DOMAIN" \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    -H "Content-Type: application/json" \
    | jq -r '.result[].id')

    if [ -z "$dns_record_ids" ]; then
        echo "No DNS records found for $subdomain.$DOMAIN"
        return 1
    fi

    # Loop through each DNS record ID and delete it
    for dns_record_id in $dns_record_ids; do
        # Send API request to delete DNS record
        curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records/$dns_record_id" \
        -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
        -H "Content-Type: application/json" \
        | jq -r '.success'
    done
}

# Function to create a new subdomain
create_subdomain() {
    echo "Creating a subdomain..."
    read -p "Enter the subdomain name: " subdomain

    if [ -z "$subdomain" ]; then
        echo "Subdomain name cannot be empty."
        exit 1
    fi

    # Create subdomain locally
    create_subdomain_local "$subdomain"

    # Create DNS record in Cloudflare
    create_dns_record_cloudflare "$subdomain" && echo "DNS record created on Cloudflare successfully."
}

# Function to delete a subdomain
delete_subdomain() {
    echo "Deleting a subdomain..."
    read -p "Enter the subdomain name: " subdomain

    if [ -z "$subdomain" ]; then
        echo "Subdomain name cannot be empty."
        exit 1
    fi

    # Delete subdomain locally
    delete_subdomain_local "$subdomain"

    # Delete DNS record in Cloudflare
    delete_dns_record_cloudflare "$subdomain" && echo "DNS records deleted on Cloudflare successfully."
}

# Main menu function
main_menu() {
    echo "Main Menu:"
    echo "1. Create a subdomain"
    echo "2. Delete a subdomain"
    echo "3. Exit"

    read -p "Please enter your choice: " choice

    case $choice in
        1) create_subdomain ;;
        2) delete_subdomain ;;
        3) sudo systemctl restart nginx
           exit ;;
        *) echo "Invalid choice. Please enter a number between 1 and 3."
           main_menu ;;
    esac
}

# Main execution
while true; do
    main_menu
done
